# Basic config
baseURL = "https://joaoduarte.dev/"
theme = "hugo-bearcub"
copyright = "João Duarte ©"
defaultContentLanguage = "pt"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[taxonomies]
   series = "series"

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    title = "João Duarte"
    languageName = "en-US 🇺🇸"
    LanguageCode = "en-US"
    contentDir = "content/en"
    [languages.en.params]
      blogPath = "/en/posts" # Path to your blog section (used by RSS)
      madeWith = "Made with [Hugo](https://gohugo.io/) and [Bear Cub](https://github.com/clente/hugo-bearcub), hosted on [Github](https://github.com)."
      description = "This is my blog, where I share some ideas :)"
  [languages.pt]
    title = "João Duarte"
    languageName = "pt-BR 🇧🇷"
    LanguageCode = "pt-BR"
    contentDir = "content/pt"
    [languages.pt.params]
      blogPath = "/posts" # Path to your blog section (used by RSS)
      madeWith = "Feito com [Hugo](https://gohugo.io/) e [Bear Cub](https://github.com/clente/hugo-bearcub), hospedado no [Github](https://github.com)."
      description = "Este é o meu blog, onde compartilho algumas ideias :)"

[params]
  author = "João Duarte"

  # The path to your favicon
  favicon = "/favicon.ico"

  # These images will show up when services want to generate a preview of a link
  # to your site. Ignored if `generateSocialCard = true`. For more information
  # about previews, see https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph
  images = ["/hugo-bearcub/images/share.webp"]

  # This title is used as the site_name on the Hugo's internal opengraph
  # structured data template
  title = "João Duarte"

  # Dates are displayed following the format below. For more information about
  # formatting, see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # If your blog is multilingual but you haven't translated a page, this theme
  # will create a disabled link. By setting `hideUntranslated` to true, you can
  # have the theme simply not show any link
  hideUntranslated = false
